In [1]:
import numpy as np

In [2]:
lista = [1,2,3,4,5,6]

array = np.array(lista)

In [3]:
print(lista)
print(type(lista))
print(array)
print(type(array))

[1, 2, 3, 4, 5, 6]
<class 'list'>
[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [4]:
arr_zeros = np.zeros(10)

print(arr_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
matriz_zeros = np.zeros((5,3))
print(matriz_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
## Notas de Alunos

lista_de_notas = [9.8, 5.6, 7.8, 9.1, 6.5]

notas = np.array(lista_de_notas)

In [11]:
print("Maximo", notas.max())
print("Minimo", notas.min())
print("Desvio Padrao", notas.std())
print("Media", notas.mean())
print("Posicao Menor", notas.argmin())

Maximo 9.8
Minimo 5.6
Desvio Padrao 1.5628179676469045
Media 7.76
Posicao Menor 1
